### ISSUE TITLE
Test Code

### ISSUE THREAD

**Issue by larizzo** [teharris1/python-insteonplm#2]
How close are you to usable code? Can I test what you have? How would I go about doing that?

**Comment by teharris1** [comment]
I am hoping to have usable code by Christmas. If not it will be early in the new year. Sorry for the delay.

The current code runs in monitor (albeit very unstable). I have been focused on the All-Link database load and have a almost 100% hit rate on finding devices by cat and subcat, which is much higher than the current code.



________________________________

**Comment by teharris1** [comment]
I now have testable code!  There are a few known issues:
1) If a message comes into the PLM during startup the process may hang
2) Some battery operated devices may not be recognized because the default has changed from just using the ALDB data for device identification to using the Get ID Record message. Battery operated devices do not respond to request messages until they first send a message. Devcat 0x10 devices (motion sensors, leak sensors, door sensors) should all work but others may not. 
3) I have not tested device overrides so someone please do :)
